In [ ]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/MBCA/1차 팀 프로젝트/데이터 파일/부산교통공사_월별 역별 권종별 승하차 정보_20241231_☆(in) (1).csv")
df

             역명         연월     승차     하차     무임  어린이   청소년
0      다대포해수욕장역   2014년 1월      0      0      0    0     0
1      다대포해수욕장역   2014년 2월      0      0      0    0     0
2      다대포해수욕장역   2014년 3월      0      0      0    0     0
3      다대포해수욕장역   2014년 4월      0      0      0    0     0
4      다대포해수욕장역   2014년 5월      0      0      0    0     0
...         ...        ...    ...    ...    ...  ...   ...
14779       안평역   2024년 8월  55604  52494  26036  472   885
14780       안평역   2024년 9월  55754  52580  25940  382   990
14781       안평역  2024년 10월  60013  57621  28537  377   952
14782       안평역  2024년 11월  59054  56638  27142  383  1040
14783       안평역  2024년 12월  59222  56500  26946  442  1062

[14784 rows x 7 columns]

In [ ]:
df['연월'] = pd.to_datetime(df['연월'], format='%Y년 %m월').dt.strftime('%Y%m')
df

             역명      연월     승차     하차     무임  어린이   청소년
0      다대포해수욕장역  201401      0      0      0    0     0
1      다대포해수욕장역  201402      0      0      0    0     0
2      다대포해수욕장역  201403      0      0      0    0     0
3      다대포해수욕장역  201404      0      0      0    0     0
4      다대포해수욕장역  201405      0      0      0    0     0
...         ...     ...    ...    ...    ...  ...   ...
14779       안평역  202408  55604  52494  26036  472   885
14780       안평역  202409  55754  52580  25940  382   990
14781       안평역  202410  60013  57621  28537  377   952
14782       안평역  202411  59054  56638  27142  383  1040
14783       안평역  202412  59222  56500  26946  442  1062

[14784 rows x 7 columns]

In [ ]:
from google.colab import files
df.to_csv('부산교통공사_월별 역별 권종별 승하차 정보_20241231_전처리완료.csv', index=False, encoding='utf-8-sig')
files.download('부산교통공사_월별 역별 권종별 승하차 정보_20241231_전처리완료.csv')

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/MBCA/1차 팀 프로젝트/데이터 파일/부산_방문자수_2020_2026_월별통합(in).csv")
df

      기준연월    연도  월    지역명  방문자수(연인원)  전년동월방문자수(재계산)  전년동월대비증감률(%)
0   Jan-20  2020  1  부산광역시   13512740            NaN           NaN
1   Feb-20  2020  2  부산광역시    9479306            NaN           NaN
2   Mar-20  2020  3  부산광역시    8356096            NaN           NaN
3   Apr-20  2020  4  부산광역시    9035890            NaN           NaN
4   May-20  2020  5  부산광역시   11105784            NaN           NaN
..     ...   ... ..    ...        ...            ...           ...
73  Feb-26  2026  2  부산광역시   13867021     11753406.0          18.0
74  Mar-26  2026  3  부산광역시   14385486     13907002.0           3.4
75  Apr-26  2026  4  부산광역시   11514954     10887390.0           5.8
76  May-26  2026  5  부산광역시   14047618     14881668.0          -5.6
77  Jun-26  2026  6  부산광역시   12015374     12654750.0          -5.1

[78 rows x 7 columns]

In [ ]:
df['연월'] = df['연도'].astype(str) + df['월'].astype(str).str.zfill(2)

df

      기준연월    연도  월    지역명  방문자수(연인원)  전년동월방문자수(재계산)  전년동월대비증감률(%)      연월
0   Jan-20  2020  1  부산광역시   13512740            NaN           NaN  202001
1   Feb-20  2020  2  부산광역시    9479306            NaN           NaN  202002
2   Mar-20  2020  3  부산광역시    8356096            NaN           NaN  202003
3   Apr-20  2020  4  부산광역시    9035890            NaN           NaN  202004
4   May-20  2020  5  부산광역시   11105784            NaN           NaN  202005
..     ...   ... ..    ...        ...            ...           ...     ...
73  Feb-26  2026  2  부산광역시   13867021     11753406.0          18.0  202602
74  Mar-26  2026  3  부산광역시   14385486     13907002.0           3.4  202603
75  Apr-26  2026  4  부산광역시   11514954     10887390.0           5.8  202604
76  May-26  2026  5  부산광역시   14047618     14881668.0          -5.6  202605
77  Jun-26  2026  6  부산광역시   12015374     12654750.0          -5.1  202606

[78 rows x 8 columns]

In [ ]:
df.drop(columns=['연도','월','기준연월'], inplace=True)
df

      지역명  방문자수(연인원)  전년동월방문자수(재계산)  전년동월대비증감률(%)      연월
0   부산광역시   13512740            NaN           NaN  202001
1   부산광역시    9479306            NaN           NaN  202002
2   부산광역시    8356096            NaN           NaN  202003
3   부산광역시    9035890            NaN           NaN  202004
4   부산광역시   11105784            NaN           NaN  202005
..    ...        ...            ...           ...     ...
73  부산광역시   13867021     11753406.0          18.0  202602
74  부산광역시   14385486     13907002.0           3.4  202603
75  부산광역시   11514954     10887390.0           5.8  202604
76  부산광역시   14047618     14881668.0          -5.6  202605
77  부산광역시   12015374     12654750.0          -5.1  202606

[78 rows x 5 columns]

In [ ]:
df =df[df['연월'] >= '202301']
df['연월'].min()

'202301'

In [ ]:
df

      지역명  방문자수(연인원)  전년동월방문자수(재계산)  전년동월대비증감률(%)      연월
36  부산광역시   13161680     11368994.0          15.8  202301
37  부산광역시   11221777      9877186.0          13.6  202302
38  부산광역시   13128549     11363376.0          15.5  202303
39  부산광역시   11330249     10067470.0          12.5  202304
40  부산광역시   12296326     11842218.0           3.8  202305
41  부산광역시   11523799     11178738.0           3.1  202306
42  부산광역시   12601932     12475754.0           1.0  202307
43  부산광역시   13071261     12622116.0           3.6  202308
44  부산광역시   13391634     12278746.0           9.1  202309
45  부산광역시   12300270     12013600.0           2.4  202310
46  부산광역시   11317982     10901740.0           3.8  202311
47  부산광역시   12699096     12020771.0           5.6  202312
48  부산광역시   12205134     13161680.0          -7.3  202401
49  부산광역시   13042704     11221777.0          16.2  202402
50  부산광역시   13459148     13128549.0           2.5  202403
51  부산광역시   10744188     11330249.0          -5.2  202404
52  부산광역시   12526098     12296326.0           1.9  202405
53  부산광역시   11750655     11523799.0           2.0  202406
54  부산광역시   12553352     12601932.0          -0.4  202407
55  부산광역시   13472851     13071261.0           3.1  202408
56  부산광역시   13618364     13391634.0           1.7  202409
57  부산광역시   12008294     12300270.0          -2.4  202410
58  부산광역시   11932462     11317982.0           5.4  202411
59  부산광역시   12926788     12699096.0           1.8  202412
60  부산광역시   14167030     12205134.0          16.1  202501
61  부산광역시   11753406     13042704.0          -9.9  202502
62  부산광역시   13907002     13459148.0           3.3  202503
63  부산광역시   10887390     10744188.0           1.3  202504
64  부산광역시   14881668     12526098.0          18.8  202505
65  부산광역시   12654750     11750655.0           7.7  202506
66  부산광역시   13879274     12553352.0          10.6  202507
67  부산광역시   14639538     13472851.0           8.7  202508
68  부산광역시   12990422     13618364.0          -4.6  202509
69  부산광역시   15551704     12008294.0          29.5  202510
70  부산광역시   13006564     11932462.0           9.0  202511
71  부산광역시   13564702     12926788.0           4.9  202512
72  부산광역시   13501618     14167030.0          -4.7  202601
73  부산광역시   13867021     11753406.0          18.0  202602
74  부산광역시   14385486     13907002.0           3.4  202603
75  부산광역시   11514954     10887390.0           5.8  202604
76  부산광역시   14047618     14881668.0          -5.6  202605
77  부산광역시   12015374     12654750.0          -5.1  202606

In [ ]:
df.to_csv('부산_방문자수_2023_2026_월별통합.csv', index=False, encoding='utf-8-sig')
files.download('부산_방문자수_2023_2026_월별통합.csv')

In [ ]:
df= pd.read_csv("/content/drive/MyDrive/MBCA/1차 팀 프로젝트/데이터 파일/부산교통공사_월별 역별 권종별 승하차 정보_전처리 완.csv")
df

             역명  행정구      연월     승차     하차     무임  어린이   청소년
0      다대포해수욕장역  사하구  201401      0      0      0    0     0
1      다대포해수욕장역  사하구  201402      0      0      0    0     0
2      다대포해수욕장역  사하구  201403      0      0      0    0     0
3      다대포해수욕장역  사하구  201404      0      0      0    0     0
4      다대포해수욕장역  사하구  201405      0      0      0    0     0
...         ...  ...     ...    ...    ...    ...  ...   ...
14779       안평역  기장군  202408  55604  52494  26036  472   885
14780       안평역  기장군  202409  55754  52580  25940  382   990
14781       안평역  기장군  202410  60013  57621  28537  377   952
14782       안평역  기장군  202411  59054  56638  27142  383  1040
14783       안평역  기장군  202412  59222  56500  26946  442  1062

[14784 rows x 8 columns]

In [ ]:
df =df[df['연월'] >= 202301]
df['연월'].min()

202301

In [ ]:
df.head()

           역명  행정구      연월      승차      하차     무임   어린이   청소년
108  다대포해수욕장역  사하구  202301  129448  103821  52690  2219  6315
109  다대포해수욕장역  사하구  202302  138690  114377  61613  2371  6274
110  다대포해수욕장역  사하구  202303  152459  125881  69208  2322  6858
111  다대포해수욕장역  사하구  202304  146779  121091  65324  2770  6238
112  다대포해수욕장역  사하구  202305  150741  123897  66907  2555  6846

In [ ]:
df

             역명  행정구      연월      승차      하차     무임   어린이   청소년
108    다대포해수욕장역  사하구  202301  129448  103821  52690  2219  6315
109    다대포해수욕장역  사하구  202302  138690  114377  61613  2371  6274
110    다대포해수욕장역  사하구  202303  152459  125881  69208  2322  6858
111    다대포해수욕장역  사하구  202304  146779  121091  65324  2770  6238
112    다대포해수욕장역  사하구  202305  150741  123897  66907  2555  6846
...         ...  ...     ...     ...     ...    ...   ...   ...
14779       안평역  기장군  202408   55604   52494  26036   472   885
14780       안평역  기장군  202409   55754   52580  25940   382   990
14781       안평역  기장군  202410   60013   57621  28537   377   952
14782       안평역  기장군  202411   59054   56638  27142   383  1040
14783       안평역  기장군  202412   59222   56500  26946   442  1062

[2688 rows x 8 columns]

In [ ]:
df.to_csv('부산교통공사_월별 역별 권종별 승하차 정보_2023_2026_전처리완.csv', index=False, encoding='utf-8-sig')
files.download('부산교통공사_월별 역별 권종별 승하차 정보_2023_2026_전처리완.csv')

In [20]:
df = pd.read_csv("/content/drive/MyDrive/MBCA/1차 팀 프로젝트/데이터 파일/busan_store_history.csv")
df.head()

,영업상태,점포명,업종대분류,업종중분류,업종명,도로명주소,인허가일,폐업일,좌표
0,폐업,충렬손칼국수,외식,분식전문점,기타 간이 음식점업,,2005-09-08,2006-11-15,POINT(129.107919799255 35.2033855635736)
1,폐업,아이엠푸드,외식,한식음식점,한식 일반 음식점업,부산광역시 동래구 충렬대로348번길 23 (낙민동),2005-09-09,2022-12-07,POINT(129.095803493488 35.1966353543051)
2,폐업,김해뒷고기,외식,한식음식점,한식 일반 음식점업,,2005-09-13,2010-11-24,POINT(129.105539275722 35.2007881729415)
3,폐업,거제횟집,외식,일식음식점,일식 음식점업,,2005-09-16,2005-12-13,POINT(129.081723635797 35.2177911632851)
4,폐업,미림레스토랑,외식,양식음식점,서양식 음식점업,,2005-09-23,2007-05-15,POINT(129.07972157347 35.2156525275316)

In [21]:
df['행정구'] = df['도로명주소'].str.extract(
    r'부산광역시\s+([가-힣]+(?:구|군))'
)

df[['도로명주소', '행정구']].head(10)

                           도로명주소  행정구
0                                 NaN
1   부산광역시 동래구 충렬대로348번길 23 (낙민동)  동래구
2                                 NaN
3                                 NaN
4                                 NaN
5   부산광역시 동래구 명륜로129번가길 12 (명륜동)  동래구
6        부산광역시 동래구 시실로 206 (명장동)  동래구
7                                 NaN
8        부산광역시 동래구 온천장로 41 (온천동)  동래구
9  부산광역시 동래구 중앙대로1267번길 69 (사직동)  동래구

In [22]:
df.head(10)

,영업상태,점포명,업종대분류,업종중분류,업종명,도로명주소,인허가일,폐업일,좌표,행정구
0,폐업,충렬손칼국수,외식,분식전문점,기타 간이 음식점업,,2005-09-08,2006-11-15,POINT(129.107919799255 35.2033855635736),NaN
1,폐업,아이엠푸드,외식,한식음식점,한식 일반 음식점업,부산광역시 동래구 충렬대로348번길 23 (낙민동),2005-09-09,2022-12-07,POINT(129.095803493488 35.1966353543051),동래구
2,폐업,김해뒷고기,외식,한식음식점,한식 일반 음식점업,,2005-09-13,2010-11-24,POINT(129.105539275722 35.2007881729415),NaN
3,폐업,거제횟집,외식,일식음식점,일식 음식점업,,2005-09-16,2005-12-13,POINT(129.081723635797 35.2177911632851),NaN
4,폐업,미림레스토랑,외식,양식음식점,서양식 음식점업,,2005-09-23,2007-05-15,POINT(129.07972157347 35.2156525275316),NaN
5,폐업,피쉬앤그릴,외식,호프·간이주점,기타 주점업,부산광역시 동래구 명륜로129번가길 12 (명륜동),2005-09-27,2015-09-04,POINT(129.081002211525 35.2057795290079),동래구
6,폐업,사랑해,외식,양식음식점,서양식 음식점업,부산광역시 동래구 시실로 206 (명장동),2005-09-29,2021-11-02,POINT(129.100792156138 35.2061365167494),동래구
7,폐업,장발단속,외식,분식전문점,기타 간이 음식점업,,2005-09-29,2006-06-09,POINT(129.069428474407 35.2066564667043),NaN
8,폐업,레츠,외식,분식전문점,기타 간이 음식점업,부산광역시 동래구 온천장로 41 (온천동),2005-09-30,2013-12-03,POINT(129.079593807977 35.2159265999779),동래구
9,폐업,일월돈까스,외식,양식음식점,서양식 음식점업,부산광역시 동래구 중앙대로1267번길 69 (사직동),2005-10-06,2019-10-16,POINT(129.074090585162 35.1991789106754),동래구

In [23]:
df[['경도', '위도']] = (
    df['좌표']
    .str.extract(r'POINT\(([-\d.]+)\s+([-\d.]+)\)')
    .astype(float)
)

df[['좌표', '경도', '위도']].head(10)

                                         좌표          경도         위도
0  POINT(129.107919799255 35.2033855635736)  129.107920  35.203386
1  POINT(129.095803493488 35.1966353543051)  129.095803  35.196635
2  POINT(129.105539275722 35.2007881729415)  129.105539  35.200788
3  POINT(129.081723635797 35.2177911632851)  129.081724  35.217791
4   POINT(129.07972157347 35.2156525275316)  129.079722  35.215653
5  POINT(129.081002211525 35.2057795290079)  129.081002  35.205780
6  POINT(129.100792156138 35.2061365167494)  129.100792  35.206137
7  POINT(129.069428474407 35.2066564667043)  129.069428  35.206656
8  POINT(129.079593807977 35.2159265999779)  129.079594  35.215927
9  POINT(129.074090585162 35.1991789106754)  129.074091  35.199179

In [24]:
!pip install geopandas
import geopandas as gpd

Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (1.1.4)
Requirement already satisfied: numpy>=1.24 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.0.2)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas) (0.13.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas) (26.2)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.2.2)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2026.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyogrio>=0.7.2->geopandas) (2026.6.17)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)

In [25]:
gu = gpd.read_file(
    '/content/drive/MyDrive/MBCA/1차 팀 프로젝트/데이터 파일/부산 시군구/BND_SIGUNGU_PG.shp'
)

In [26]:
gu.head()

,BASE_DATE,SIGUNGU_CD,SIGUNGU_NM,geometry
0,20250630,11010,종로구,"POLYGON ((197800.72 559064.245, 197782.581 558..."
1,20250630,11020,중구,"POLYGON ((202043.919 552491.141, 202063.481 55..."
2,20250630,11030,용산구,"POLYGON ((197275.979 550595.299, 197275.977 55..."
3,20250630,11040,성동구,"POLYGON ((203535.345 552606.268, 203569.567 55..."
4,20250630,11050,광진구,"POLYGON ((208981.056 552544.566, 209031.744 55..."

In [28]:
gu.columns

Index(['BASE_DATE', 'SIGUNGU_CD', 'SIGUNGU_NM', 'geometry'], dtype='object')

In [29]:
gu.crs

<Projected CRS: EPSG:5186>
Name: KGD2002 / Central Belt 2010
Axis Info [cartesian]:
- X[north]: Northing (metre)
- Y[east]: Easting (metre)
Area of Use:
- name: Republic of Korea (South Korea) - onshore between 126°E and 128°E.
- bounds: (126.0, 33.14, 128.0, 38.33)
Coordinate Operation:
- name: Korea Central Belt 2010
- method: Transverse Mercator
Datum: Korean Geodetic Datum 2002
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [31]:
busan_gu = gu[
    gu['SIGUNGU_CD'].astype(str).str.startswith('21')
].copy()

busan_gu[['SIGUNGU_CD', 'SIGUNGU_NM']]

   SIGUNGU_CD SIGUNGU_NM
25      21010         중구
26      21020         서구
27      21030         동구
28      21040        영도구
29      21050       부산진구
30      21060        동래구
31      21070         남구
32      21080         북구
33      21090       해운대구
34      21100        사하구
35      21110        금정구
36      21120        강서구
37      21130        연제구
38      21140        수영구
39      21150        사상구
40      21510        기장군

In [32]:
busan_gu = busan_gu.to_crs(epsg=4326)
busan_gu.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [33]:
df[['경도','위도']].isna().sum()

경도    0
위도    0
dtype: int64

In [35]:
valid_df = df[
    df['경도'].notna() &
    df['위도'].notna()
].copy()

In [36]:
import geopandas as gpd

gdf = gpd.GeoDataFrame(
    valid_df,
    geometry=gpd.points_from_xy(
        valid_df['경도'],
        valid_df['위도']
    ),
    crs='EPSG:4326'
)

In [37]:
result = gpd.sjoin(
    gdf,
    busan_gu[['SIGUNGU_NM', 'geometry']],
    how='left',
    predicate='within'
)

In [38]:
result = result.rename(
    columns={'SIGUNGU_NM': '행정구'}
)

In [39]:
result[
    ['점포명', '도로명주소', '좌표', '행정구']
].head()

,점포명,도로명주소,좌표,행정구,행정구
0,충렬손칼국수,,POINT(129.107919799255 35.2033855635736),NaN,동래구
1,아이엠푸드,부산광역시 동래구 충렬대로348번길 23 (낙민동),POINT(129.095803493488 35.1966353543051),동래구,동래구
2,김해뒷고기,,POINT(129.105539275722 35.2007881729415),NaN,동래구
3,거제횟집,,POINT(129.081723635797 35.2177911632851),NaN,동래구
4,미림레스토랑,,POINT(129.07972157347 35.2156525275316),NaN,동래구

In [40]:
result.head(10)

,영업상태,점포명,업종대분류,업종중분류,업종명,도로명주소,인허가일,폐업일,좌표,행정구,경도,위도,geometry,index_right,행정구
0,폐업,충렬손칼국수,외식,분식전문점,기타 간이 음식점업,,2005-09-08,2006-11-15,POINT(129.107919799255 35.2033855635736),NaN,129.107920,35.203386,POINT (129.10792 35.20339),30,동래구
1,폐업,아이엠푸드,외식,한식음식점,한식 일반 음식점업,부산광역시 동래구 충렬대로348번길 23 (낙민동),2005-09-09,2022-12-07,POINT(129.095803493488 35.1966353543051),동래구,129.095803,35.196635,POINT (129.0958 35.19664),30,동래구
2,폐업,김해뒷고기,외식,한식음식점,한식 일반 음식점업,,2005-09-13,2010-11-24,POINT(129.105539275722 35.2007881729415),NaN,129.105539,35.200788,POINT (129.10554 35.20079),30,동래구
3,폐업,거제횟집,외식,일식음식점,일식 음식점업,,2005-09-16,2005-12-13,POINT(129.081723635797 35.2177911632851),NaN,129.081724,35.217791,POINT (129.08172 35.21779),30,동래구
4,폐업,미림레스토랑,외식,양식음식점,서양식 음식점업,,2005-09-23,2007-05-15,POINT(129.07972157347 35.2156525275316),NaN,129.079722,35.215653,POINT (129.07972 35.21565),30,동래구
5,폐업,피쉬앤그릴,외식,호프·간이주점,기타 주점업,부산광역시 동래구 명륜로129번가길 12 (명륜동),2005-09-27,2015-09-04,POINT(129.081002211525 35.2057795290079),동래구,129.081002,35.205780,POINT (129.081 35.20578),30,동래구
6,폐업,사랑해,외식,양식음식점,서양식 음식점업,부산광역시 동래구 시실로 206 (명장동),2005-09-29,2021-11-02,POINT(129.100792156138 35.2061365167494),동래구,129.100792,35.206137,POINT (129.10079 35.20614),30,동래구
7,폐업,장발단속,외식,분식전문점,기타 간이 음식점업,,2005-09-29,2006-06-09,POINT(129.069428474407 35.2066564667043),NaN,129.069428,35.206656,POINT (129.06943 35.20666),30,동래구
8,폐업,레츠,외식,분식전문점,기타 간이 음식점업,부산광역시 동래구 온천장로 41 (온천동),2005-09-30,2013-12-03,POINT(129.079593807977 35.2159265999779),동래구,129.079594,35.215927,POINT (129.07959 35.21593),30,동래구
9,폐업,일월돈까스,외식,양식음식점,서양식 음식점업,부산광역시 동래구 중앙대로1267번길 69 (사직동),2005-10-06,2019-10-16,POINT(129.074090585162 35.1991789106754),동래구,129.074091,35.199179,POINT (129.07409 35.19918),30,동래구

In [41]:
result.tail(10)

,영업상태,점포명,업종대분류,업종중분류,업종명,도로명주소,인허가일,폐업일,좌표,행정구,경도,위도,geometry,index_right,행정구
336225,폐업,지오마켓,소매,전자상거래업,전자상거래업,"부산광역시 부산진구 시민공원로19번길 54 (부암동,삼부로얄아파트)",2010-12-21,2011-04-19,POINT(129.051744644577 35.1658245174784),부산진구,129.051745,35.165825,POINT (129.05174 35.16582),29,부산진구
336226,취소/말소/만료/정지/중지,오늘도 빛날 당신에게,,,,부산광역시 부산진구 신천대로204번길 25 (부암동),2020-04-21,,POINT(129.05157236671 35.1604241409649),부산진구,129.051572,35.160424,POINT (129.05157 35.16042),29,부산진구
336227,영업/정상,업스포츠,소매,전자상거래업,전자상거래업,부산광역시 연제구 고분로 48 (연산동),2019-07-30,,POINT(129.087558996332 35.1854397123398),연제구,129.087559,35.185440,POINT (129.08756 35.18544),37,연제구
336228,영업/정상,단블리,소매,전자상거래업,전자상거래업,부산광역시 연제구 고분로105번길 12 (연산동),2021-07-28,,POINT(129.094073158097 35.1865016344006),연제구,129.094073,35.186502,POINT (129.09407 35.1865),37,연제구
336229,영업/정상,리멤버마이엔젤,소매,전자상거래업,전자상거래업,부산광역시 연제구 연동로 13 (연산동),2023-01-18,,POINT(129.093359725815 35.1879092676555),연제구,129.093360,35.187909,POINT (129.09336 35.18791),37,연제구
336230,영업/정상,참월드,소매,전자상거래업,전자상거래업,부산광역시 연제구 연동로13번길 19 (연산동),2020-07-29,,POINT(129.094228467283 35.1876412214555),연제구,129.094228,35.187641,POINT (129.09423 35.18764),37,연제구
336231,영업/정상,힐링캠프,소매,전자상거래업,전자상거래업,"부산광역시 연제구 과정로294번길 21 (연산동,연제타워)",2020-03-20,,POINT(129.094824971427 35.1891609345106),연제구,129.094825,35.189161,POINT (129.09482 35.18916),37,연제구
336232,폐업,일성상사,소매,전자상거래업,전자상거래업,부산광역시 연제구 과정로 300 (연산동),2007-10-17,2018-01-23,POINT(129.094725877425 35.1889456671042),연제구,129.094726,35.188946,POINT (129.09473 35.18895),37,연제구
336233,영업/정상,이에프비엔비(EF B&B),소매,전자상거래업,전자상거래업,부산광역시 연제구 과정로 298 (연산동),2020-09-07,,POINT(129.094874432959 35.1889044013805),연제구,129.094874,35.188904,POINT (129.09487 35.1889),37,연제구
336234,영업,오피엘,서비스,부동산,부동산,부산광역시 부산진구 중앙대로,,,POINT(129.0585392 35.14873305),부산진구,129.058539,35.148733,POINT (129.05854 35.14873),29,부산진구

In [42]:
result.to_csv('busan_store_history_v1.csv', index=False, encoding='utf-8-sig')
files.download('busan_store_history_v1.csv')

In [43]:
df= pd.read_csv("/content/drive/MyDrive/MBCA/1차 팀 프로젝트/데이터 파일/busan_store_history_v1.csv")
df.head(10)

,영업상태,점포명,업종대분류,업종중분류,업종명,행정구,인허가일,폐업일,경도,위도
0,폐업,충렬손칼국수,외식,분식전문점,기타 간이 음식점업,동래구,2005-09-08,2006-11-15,129.107920,35.203386
1,폐업,아이엠푸드,외식,한식음식점,한식 일반 음식점업,동래구,2005-09-09,2022-12-07,129.095803,35.196635
2,폐업,김해뒷고기,외식,한식음식점,한식 일반 음식점업,동래구,2005-09-13,2010-11-24,129.105539,35.200788
3,폐업,거제횟집,외식,일식음식점,일식 음식점업,동래구,2005-09-16,2005-12-13,129.081724,35.217791
4,폐업,미림레스토랑,외식,양식음식점,서양식 음식점업,동래구,2005-09-23,2007-05-15,129.079722,35.215653
5,폐업,피쉬앤그릴,외식,호프·간이주점,기타 주점업,동래구,2005-09-27,2015-09-04,129.081002,35.205780
6,폐업,사랑해,외식,양식음식점,서양식 음식점업,동래구,2005-09-29,2021-11-02,129.100792,35.206137
7,폐업,장발단속,외식,분식전문점,기타 간이 음식점업,동래구,2005-09-29,2006-06-09,129.069428,35.206656
8,폐업,레츠,외식,분식전문점,기타 간이 음식점업,동래구,2005-09-30,2013-12-03,129.079594,35.215927
9,폐업,일월돈까스,외식,양식음식점,서양식 음식점업,동래구,2005-10-06,2019-10-16,129.074091,35.199179

In [44]:
df['인허가일'] = pd.to_datetime(df['인허가일'], errors='coerce').dt.strftime('%Y%m')

df['폐업일'] = df['폐업일'].replace(r'^\s*$', pd.NA, regex=True)

df['폐업일'] = (
     pd.to_datetime(df['폐업일'], errors='coerce')
     .dt.strftime('%Y%m')
     .fillna('')
)

df.head(10)

,영업상태,점포명,업종대분류,업종중분류,업종명,행정구,인허가일,폐업일,경도,위도
0,폐업,충렬손칼국수,외식,분식전문점,기타 간이 음식점업,동래구,200509,200611,129.107920,35.203386
1,폐업,아이엠푸드,외식,한식음식점,한식 일반 음식점업,동래구,200509,202212,129.095803,35.196635
2,폐업,김해뒷고기,외식,한식음식점,한식 일반 음식점업,동래구,200509,201011,129.105539,35.200788
3,폐업,거제횟집,외식,일식음식점,일식 음식점업,동래구,200509,200512,129.081724,35.217791
4,폐업,미림레스토랑,외식,양식음식점,서양식 음식점업,동래구,200509,200705,129.079722,35.215653
5,폐업,피쉬앤그릴,외식,호프·간이주점,기타 주점업,동래구,200509,201509,129.081002,35.205780
6,폐업,사랑해,외식,양식음식점,서양식 음식점업,동래구,200509,202111,129.100792,35.206137
7,폐업,장발단속,외식,분식전문점,기타 간이 음식점업,동래구,200509,200606,129.069428,35.206656
8,폐업,레츠,외식,분식전문점,기타 간이 음식점업,동래구,200509,201312,129.079594,35.215927
9,폐업,일월돈까스,외식,양식음식점,서양식 음식점업,동래구,200510,201910,129.074091,35.199179

In [45]:
df.tail(20)

,영업상태,점포명,업종대분류,업종중분류,업종명,행정구,인허가일,폐업일,경도,위도
336215,폐업,쏙쏙,소매,전자상거래업,전자상거래업,부산진구,201108,201206,129.050860,35.166003
336216,폐업,(사)한국휘트니스협회,소매,전자상거래업,전자상거래업,중구,200709,201012,129.029222,35.097627
336217,폐업,키스마이스킨(한길시스템),소매,전자상거래업,전자상거래업,부산진구,201104,201310,129.050860,35.166003
336218,취소/말소/만료/정지/중지,(주)피크,소매,전자상거래업,전자상거래업,부산진구,200904,,129.050860,35.166003
336219,영업/정상,르미어리,소매,전자상거래업,전자상거래업,부산진구,201904,,129.050632,35.164526
336220,폐업,다이어트 go119,소매,전자상거래업,전자상거래업,부산진구,201508,201601,129.050632,35.164526
336221,취소/말소/만료/정지/중지,부산가구아울렛,소매,전자상거래업,전자상거래업,부산진구,201408,,129.050632,35.164526
336222,폐업,베비스앤코,소매,전자상거래업,전자상거래업,부산진구,202102,202301,129.051009,35.163229
336223,폐업,디자인나타레,소매,전자상거래업,전자상거래업,부산진구,200711,201602,129.051120,35.163756
336224,폐업,마미코튼,소매,전자상거래업,전자상거래업,부산진구,202011,202103,129.051120,35.163756
336225,폐업,지오마켓,소매,전자상거래업,전자상거래업,부산진구,201012,201104,129.051745,35.165825
336226,취소/말소/만료/정지/중지,오늘도 빛날 당신에게,,,,부산진구,202004,,129.051572,35.160424
336227,영업/정상,업스포츠,소매,전자상거래업,전자상거래업,연제구,201907,,129.087559,35.185440
336228,영업/정상,단블리,소매,전자상거래업,전자상거래업,연제구,202107,,129.094073,35.186502
336229,영업/정상,리멤버마이엔젤,소매,전자상거래업,전자상거래업,연제구,202301,,129.093360,35.187909
336230,영업/정상,참월드,소매,전자상거래업,전자상거래업,연제구,202007,,129.094229,35.187641
336231,영업/정상,힐링캠프,소매,전자상거래업,전자상거래업,연제구,202003,,129.094825,35.189161
336232,폐업,일성상사,소매,전자상거래업,전자상거래업,연제구,200710,201801,129.094726,35.188946
336233,영업/정상,이에프비엔비(EF B&B),소매,전자상거래업,전자상거래업,연제구,202009,,129.094874,35.188904
336234,영업,오피엘,서비스,부동산,부동산,부산진구,NaN,,129.058539,35.148733

In [50]:
df.to_csv('busan_store_history_v2.csv', index=False, encoding='utf-8-sig')
files.download('busan_store_history_v2.csv')

In [47]:
df = df[
    (df['폐업일'] == '') |
    (df['폐업일'] >= '202301')
].copy()

df.tail(20)

,영업상태,점포명,업종대분류,업종중분류,업종명,행정구,인허가일,폐업일,경도,위도
336206,영업/정상,브라운스토어,소매,전자상거래업,전자상거래업,부산진구,201207,,129.049370,35.183344
336207,취소/말소/만료/정지/중지,코코야,소매,전자상거래업,전자상거래업,동래구,201008,,129.106396,35.204203
336208,영업/정상,주식회사 제니원,,,,부산진구,202006,,129.047476,35.185597
336209,취소/말소/만료/정지/중지,모든오피스,소매,전자상거래업,전자상거래업,부산진구,200807,,129.048317,35.188210
336210,취소/말소/만료/정지/중지,니옷네옷,소매,전자상거래업,전자상거래업,부산진구,201911,,129.053236,35.182467
336211,영업/정상,나무그늘아래,소매,전자상거래업,전자상거래업,부산진구,202102,,129.054853,35.181723
336212,취소/말소/만료/정지/중지,멀티킹,소매,전자상거래업,전자상거래업,부산진구,200806,,129.052830,35.181811
336214,영업/정상,봄인 디자인(BOM_in Design),소매,전자상거래업,전자상거래업,부산진구,202106,,129.051823,35.168774
336218,취소/말소/만료/정지/중지,(주)피크,소매,전자상거래업,전자상거래업,부산진구,200904,,129.050860,35.166003
336219,영업/정상,르미어리,소매,전자상거래업,전자상거래업,부산진구,201904,,129.050632,35.164526
336221,취소/말소/만료/정지/중지,부산가구아울렛,소매,전자상거래업,전자상거래업,부산진구,201408,,129.050632,35.164526
336222,폐업,베비스앤코,소매,전자상거래업,전자상거래업,부산진구,202102,202301,129.051009,35.163229
336226,취소/말소/만료/정지/중지,오늘도 빛날 당신에게,,,,부산진구,202004,,129.051572,35.160424
336227,영업/정상,업스포츠,소매,전자상거래업,전자상거래업,연제구,201907,,129.087559,35.185440
336228,영업/정상,단블리,소매,전자상거래업,전자상거래업,연제구,202107,,129.094073,35.186502
336229,영업/정상,리멤버마이엔젤,소매,전자상거래업,전자상거래업,연제구,202301,,129.093360,35.187909
336230,영업/정상,참월드,소매,전자상거래업,전자상거래업,연제구,202007,,129.094229,35.187641
336231,영업/정상,힐링캠프,소매,전자상거래업,전자상거래업,연제구,202003,,129.094825,35.189161
336233,영업/정상,이에프비엔비(EF B&B),소매,전자상거래업,전자상거래업,연제구,202009,,129.094874,35.188904
336234,영업,오피엘,서비스,부동산,부동산,부산진구,NaN,,129.058539,35.148733

In [48]:
df.head()

,영업상태,점포명,업종대분류,업종중분류,업종명,행정구,인허가일,폐업일,경도,위도
33,폐업,신대감 연탄불고기와 돌솥쌈밥,외식,한식음식점,한식 일반 음식점업,강서구,201506,202303,128.956651,35.179003
35,폐업,비턴,외식,호프·간이주점,기타 주점업,강서구,201311,202302,128.903270,35.081402
39,폐업,맛고축산,외식,한식음식점,한식 일반 음식점업,강서구,201507,202304,128.902993,35.083251
193,폐업,봉구비어 학장점,외식,한식음식점,한식 일반 음식점업,사상구,200305,202303,128.980431,35.139776
316,폐업,삼정원반점,외식,중식음식점,중식 음식점업,수영구,198411,202304,129.117234,35.159966

In [49]:
df = df[
    df['영업상태'].astype(str).str.strip() != '취소/말소/만료/정지/중지'
].copy()

df.tail(10)

,영업상태,점포명,업종대분류,업종중분류,업종명,행정구,인허가일,폐업일,경도,위도
336214,영업/정상,봄인 디자인(BOM_in Design),소매,전자상거래업,전자상거래업,부산진구,202106,,129.051823,35.168774
336219,영업/정상,르미어리,소매,전자상거래업,전자상거래업,부산진구,201904,,129.050632,35.164526
336222,폐업,베비스앤코,소매,전자상거래업,전자상거래업,부산진구,202102,202301,129.051009,35.163229
336227,영업/정상,업스포츠,소매,전자상거래업,전자상거래업,연제구,201907,,129.087559,35.185440
336228,영업/정상,단블리,소매,전자상거래업,전자상거래업,연제구,202107,,129.094073,35.186502
336229,영업/정상,리멤버마이엔젤,소매,전자상거래업,전자상거래업,연제구,202301,,129.093360,35.187909
336230,영업/정상,참월드,소매,전자상거래업,전자상거래업,연제구,202007,,129.094229,35.187641
336231,영업/정상,힐링캠프,소매,전자상거래업,전자상거래업,연제구,202003,,129.094825,35.189161
336233,영업/정상,이에프비엔비(EF B&B),소매,전자상거래업,전자상거래업,연제구,202009,,129.094874,35.188904
336234,영업,오피엘,서비스,부동산,부동산,부산진구,NaN,,129.058539,35.148733

In [51]:
df.to_csv('busan_store_history_v3.csv', index=False, encoding='utf-8-sig')
files.download('busan_store_history_v3.csv')