In [1]:
# 파일 업로드

from google.colab import files

uploaded = files.upload()

Saving 방문자수_히트맵_외국인_통합.csv to 방문자수_히트맵_외국인_통합.csv
Saving 방문자수_히트맵_외지인_통합.csv to 방문자수_히트맵_외지인_통합.csv
Saving 방문자수_히트맵_현지인_통합.csv to 방문자수_히트맵_현지인_통합.csv

In [2]:
# 파일 이름 확인

uploaded.keys()

dict_keys(['방문자수_히트맵_외국인_통합.csv', '방문자수_히트맵_외지인_통합.csv', '방문자수_히트맵_현지인_통합.csv'])

In [5]:
# 파일 읽어보기

import pandas as pd

외지인 = pd.read_csv('방문자수_히트맵_외지인_통합.csv')
현지인 = pd.read_csv('방문자수_히트맵_현지인_통합.csv')
외국인 = pd.read_csv('방문자수_히트맵_외국인_통합.csv')

print(외지인.shape)
print(외지인.columns)
display(외지인.head())

(672, 4)
Index(['기준연월', '기초지자체', '방문자 수', '구분'], dtype='object')

     기준연월 기초지자체    방문자 수       구분
0  202301   강서구  3381336  외지인 방문자
1  202301   금정구  2425745  외지인 방문자
2  202301   기장군  3759980  외지인 방문자
3  202301    남구  2470836  외지인 방문자
4  202301    동구  2645570  외지인 방문자

In [6]:
# 컬럼명 통합(변경)

외지인 = 외지인.rename(columns={
    '기준연월': '연월',
    '기초지자체': '행정구명',
    '방문자 수': '외지인'
})

현지인 = 현지인.rename(columns={
    '기준연월': '연월',
    '기초지자체': '행정구명',
    '방문자 수': '현지인'
})

외국인 = 외국인.rename(columns={
    '기준연월': '연월',
    '지역': '행정구명',
    '외국인 방문자 수': '외국인'
})

In [7]:
# 필요한 컬럼만 남기기
외지인 = 외지인[['연월', '행정구명', '외지인']]
현지인 = 현지인[['연월', '행정구명', '현지인']]
외국인 = 외국인[['연월', '행정구명', '외국인']]

In [8]:
# 세 파일 합치기

방문자 = 외지인.merge(
    현지인,
    on=['연월', '행정구명'],
    how='inner'
)

방문자 = 방문자.merge(
    외국인,
    on=['연월', '행정구명'],
    how='inner'
)

In [9]:
# 전체 방문자수 계산

방문자['전체'] = (
    방문자['외지인']
    + 방문자['현지인']
    + 방문자['외국인']
)

In [10]:
# 컬럼 순서 변경

방문자 = 방문자[
    ['행정구명', '연월', '외지인', '현지인', '외국인', '전체']
]

In [11]:
# 확인

print(방문자.columns)
display(방문자.head())

Index(['행정구명', '연월', '외지인', '현지인', '외국인', '전체'], dtype='object')

  행정구명      연월      외지인      현지인     외국인       전체
0  강서구  202301  3381336  2415172  116492  5913000
1  금정구  202301  2425745  3791823   11984  6229552
2  기장군  202301  3759980  2862748   44563  6667291
3   남구  202301  2470836  4333217   46794  6850847
4   동구  202301  2645570  1401824   37029  4084423

In [12]:
print('행 수:', len(방문자))
print('행정구 수:', 방문자['행정구명'].nunique())
print('연월 수:', 방문자['연월'].nunique())
print('중복:', 방문자.duplicated(['행정구명', '연월']).sum())

행 수: 656
행정구 수: 16
연월 수: 41
중복: 0